app_root: .
ignored_folders:
- cli
- cmd
- vendor
- log
- logs
- assets
- public
- grifts
- tmp
- bin
- node_modules
- .sass-cache
- bazel-bin
- bazel-genfiles
- bazel-macaroons_authz
- bazel-out
- bazel-testlogs
- java
- javascript
- cli
included_extensions:
- .go
- .env
build_path: tmp
build_delay: 200ns
binary_name: macaroons-authz-build
command_flags: []
enable_colors: true
log_name: buffalo
