version '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=authz
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  login:
    image: Dockerfiles/Dockerfile.login
