---
- name: Setup Ansible
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/ansible

- name: Install CFSSL
  hosts: all
  environment:
    GOPATH: /usr/local/gopath
  vars:
    version: "master"
    goroot: /usr/local/goroot
    cfssl_root: /cfssl
    go_binary: go1.11.2.linux-amd64.tar.gz
  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - gcc

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ goroot }}"
        - "{{ ansible_env.GOPATH }}"
        - "{{ cfssl_root }}/config"
        - "{{ cfssl_root }}/keys"

    - name: Download GO
      get_url:
        url: "https://dl.google.com/go/{{ go_binary }}"
        dest: "{{ goroot }}/{{ go_binary }}"
        checksum: sha256:1dfe664fa3d8ad714bbd15a36627992effd150ddabd7523931f077b3926d736d
        # This is a hack to work around some networks, it needs to be removed.
        validate_certs: no

    - name: Install GO
      unarchive:
        remote_src: yes
        src: "{{ goroot }}/{{ go_binary }}"
        dest: "{{ goroot }}"

    - name: Symlink GO
      file:
        src: "{{ goroot }}/go/bin/go"
        dest: /usr/bin/go
        state: link

    - name: Build and install CFSSL
      command: go get -u github.com/cloudflare/cfssl/cmd/cfssl

    - name: Symlink CFSSL
      file:
        src: "{{ ansible_env.GOPATH }}/bin/cfssl"
        dest: /usr/bin/cfssl
        state: link

- name: Copy required data
  hosts: all
  tasks:
    - name: Copy entrypoint
      copy:
        src: ./cfssl-entrypoint.sh
        dest: /usr/bin
        mode: o+x

    - name: Copy CFSSL config file
      copy:
        src: ../cfssl/config/config_ca.json
        dest: /cfssl/config

    - name: Copy CFSSL keys
      copy:
        src: "{{ item }}"
        dest: /cfssl/keys
      with_fileglob:
        - ../cfssl/keys/*

- name: Cleanup
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/cleanup
    - name: Remove packages
      package:
        name: "{{ item }}"
        state: absent
      with_items:
        - gcc
        - git
        
