---
- name: Setup Ansible
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/ansible

- name: Install CFSSL
  hosts: all
  environment:
    GOPATH: /usr/local/gopath
  vars:
    version: "master"
    goroot: /usr/local/goroot
    cfssl_root: /cfssl
  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - gcc

    - name: create directories directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ goroot }}"
        - "{{ ansible_env.GOPATH }}"
        - "{{ cfssl_root }}/config"
        - "{{ cfssl_root }}/keys"

    - name: install go
      unarchive:
        remote_src: yes
        src: https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
        dest: "{{ goroot }}"

    - name: symlink go
      file:
        src: "{{ goroot }}/go/bin/go"
        dest: /usr/bin/go
        state: link

    - name: install cfssl
      command: go get -u github.com/cloudflare/cfssl/cmd/cfssl

    - name: symlink cfssl
      file:
        src: "{{ ansible_env.GOPATH }}/bin/cfssl"
        dest: /usr/bin/cfssl
        state: link

- name: Copy required data
  hosts: all
  tasks:
    - name: Copy Entrypoint
      copy:
        src: ./cfssl-entrypoint.sh
        dest: /usr/bin
        mode: o+x

    - name: Copy CFSSL config file
      copy:
        src: ../cfssl/config/config_ca.json
        dest: /cfssl/config

    - name: Copy CFSSL keys
      copy:
        src: "{{ item }}"
        dest: /cfssl/keys
      with_fileglob:
        - ../cfssl/keys/*

- name: Cleanup
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/cleanup
    - name: remove packages
      package:
        name: "{{ item }}"
        state: absent
      with_items:
        - gcc
        - git
        
