---
- name: Setup Ansible
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/ansible

- name: Setup CMS AuthZ
  hosts: all
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /authz/db
    - name: Install curl
      package:
        name: curl
        state: present
    - name: Copy binary
      copy:
        src: ../bin/cms_authz_linux
        dest: /usr/bin
        mode: o+x
    - name: Copy entryscript
      copy:
        src: ./authz-entrypoint.sh
        dest: /usr/bin
        mode: o+x
    - name: Copy test keys
      copy:
        src: ../user_keys.json
        dest: /authz
    - name: Copy DB Seeds
      copy:
        src: "{{ item }}"
        dest: /authz/db
      with_fileglob:
        - ../db/seeds_*

- name: Cleanup
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/cleanup
