---
- name: Setup Ansible
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/ansible

- name: Setup system
  hosts: all
  tasks:
    - name: Install system dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /authz/db
    - name: Download Buffalo
      get_url:
        url: https://github.com/gobuffalo/buffalo/releases/download/v0.13.10/buffalo_0.13.10_linux_amd64.tar.gz
        dest: /authz
        checksum: sha256:7af64129190a44fbac6fcfc2cd3521abc0e081ec404b10febabac822e6a4d4f3
    - name: Install Buffalo
      unarchive:
        remote_src: yes
        src: /authz/buffalo_0.13.10_linux_amd64.tar.gz
        dest: /usr/local/bin

- name: Setup CMS AuthZ
  hosts: all
  vars:
    authz_root: /authz
  tasks:
    - name: Copy binary
      copy:
        src: ../bin/cms_authz_linux
        dest: /usr/bin
        mode: o+x
    - name: Copy entryscript
      copy:
        src: ./authz-entrypoint.sh
        dest: /usr/bin
        mode: o+x
    - name: Copy test keys
      copy:
        src: ../user_keys.json
        dest: "{{ authz_root }}"
    - name: Copy DB Seeds
      copy:
        src: "{{ item }}"
        dest: "{{ authz_root }}/db"
      with_fileglob:
        - ../db/seeds_*
    - name: Copy Env file
      copy:
        src: ../.env
        dest: "{{ authz_root }}"

- name: Cleanup
  hosts: all
  gather_facts: no
  tasks:
    - include_role:
        name: ../roles/cleanup
